### ISSUE TITLE
Moving to DCOS-LABS

### ISSUE THREAD

**Issue by fabianbaier** [vishnu2kmohan/beakerx-dcos-docker#3]
Hi Vishnu,

To better consolidate and combine as discussed moving forward we want this repo to live here: https://github.com/dcos-labs/dcos-beakerx-service

Can you move it? (@joerg84 added you to the repo)

Best,
Fabian

**Comment by joerg84** [comment]
Thanks @vishnu2kmohan  for moving it here: https://github.com/dcos-labs/dcos-jupyter-service

**Comment by vishnu2kmohan** [comment]
It is done!

**Comment by fabianbaier** [comment]
Yay

Awesome

**Comment by scottdraves** [comment]
🐬
